:whale: Fix girder docker build
girder/girder pull request #3377
Opened 2022-02-22 09:22 UTC by Gjacquenot

This update fixes issue https://github.com/girder/girder/issues/3305, where docker build failed

The build error we had is presented below

The Dockerfile also installs all plugins.

I am open to suggestion to improve the Dockerfile. I think the docker build should also be included in the CI.

```
Step 12/13 : RUN girder build
 ---> Running in f7793f217cd8
Traceback (most recent call last):
  File "/usr/bin/girder", line 33, in <module>
    sys.exit(load_entry_point('girder', 'console_scripts', 'girder')())
  File "/usr/bin/girder", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 947, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 538, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for girder
The command '/bin/sh -c girder build' returned a non-zero code: 1
```

It would be nice to fix this and make a docker build in the CI!

2022-02-22 09:37 UTC, Gjacquenot commented
@zachmullen @manthey, for your information!

2022-02-23 01:30 UTC, zachmullen requested changes

2022-02-23 01:30 UTC, zachmullen commented on Dockerfile
> +# RUN python3 -m pip install --upgrade --upgrade-strategy eager --editable .
Let's delete this line if we no longer need it.

2022-02-23 01:31 UTC, zachmullen commented on Dockerfile
> +# RUN python3 -m pip install --upgrade --upgrade-strategy eager --editable .
```suggestion
```

2022-02-23 12:56 UTC, zachmullen commented on Dockerfile
> + && cd ..
This part (installing all plugins) seems unrelated to the bugfix, and could potentially require more discussion as to whether it's appropriate. Could we make that as a separate PR so we can get the bugfix part merged easily?

2022-02-23 15:22 UTC, zachmullen approved these changes
Thanks @Gjacquenot for the fix!

2022-02-23 15:24 UTC, merged